# Generated by Django 4.2 on 2023-04-25 19:24

import django.core.validators
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email address!')])),
                ('gender', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1)])),
                ('phone_prefix', models.IntegerField()),
                ('phone', models.CharField(help_text='Enter a 7-digit phone number.', max_length=7, validators=[django.core.validators.RegexValidator(message='Phone number must be 7 digits and cannot start with 0, 1, or 2.', regex='^[3-9]\\d{6}$')])),
                ('gov_prefix_id', models.IntegerField(choices=[(1, 'AZE'), (2, 'AA'), (3, 'MYI'), (4, 'DYI')], validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)])),
                ('gov_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999)])),
                ('fin_code', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('client_code', models.IntegerField(default=user.models.custom_sequence)),
                ('monthyly_expenses', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('is_active', models.IntegerField(default=1)),
                ('is_blocked', models.IntegerField(default=0)),
                ('selected_local_warehouse_id', models.IntegerField()),
            ],
        ),
    ]
